### ISSUE TITLE
Error code 6. Not enough funds

### ISSUE THREAD

**Issue by amnesia106** [btdex/btdex#6] opened 2019-12-29 21:49 UTC
![Bildschirmfoto 2019-12-29 um 22 46 55](https://user-images.githubusercontent.com/40226796/71563292-408d9f80-2a8d-11ea-8f0c-608eb03fe68a.png)

**Comment by jjos2372** [comment] 2019-12-29 22:45
Thanks for reporting, I could not reproduce the problem. Is this permanent or was just a temporary problem? This message would be shown only if you had less than 6 BURST on your account.

**Comment by milkmoney364** [comment] 2019-12-30 00:03
I was impressed that BTDEX did not allow me to sell funds that were also up for sale. If I had a sell order for 100 Burst and had 105 Burst total in my wallet - only 5 are available. Wondering if this happened here? Was there a sell order in this situation?

**Comment by jjos2372** [comment] 2019-12-30 00:25
That is actually a BRS error, not actually BTDEX. Please just confirm that you had other open orders such that your balance would not be enough if they were all filled. In this case BRS refuses to place your new order due to not enough funds.

**Comment by jjos2372** [comment] 2019-12-30 10:38
The amount in *bids* is now shown as *locked* and reduced from the balance to avoid any confusion: 
![image](https://user-images.githubusercontent.com/31958515/71578450-f6c9a700-2ad6-11ea-8dd7-c66e0e8838bc.png)

Fixed on: 06c01ffbb3d780ef8817a4f9501b5629aa684581

**Closed by jjos2372** 2019-12-30 10:38 UTC
