### ISSUE TITLE
On my mac I don't see the mining tab

### ISSUE THREAD

**Issue by joostschouten** [btdex/btdex#144] opened 2021-04-01 22:07 UTC
I'd love to start playing with the new plotting feature but the tab does not show for me on v0.4 and v0.4.1. Is there a setting I'm missing or is mac not yet supported?

<img width="631" alt="Screenshot 2021-04-02 at 11 05 50" src="https://user-images.githubusercontent.com/198939/113359122-985b3a80-93a3-11eb-8b2d-9eee9f452490.png">

**Comment by jjos2372** [comment] 2021-04-02 01:01
Hello, the problem is we don't have binary builds for the plotter and miner for mac at the moment. This is the reason to have them disabled. Could you check if you can build engraver and scavenger from sources without issues on your machine?

**Comment by jjos2372** [comment] 2021-07-03 20:12
Fixed on the latest release.

**Closed by jjos2372** 2021-07-03 20:12 UTC
